name: Golang CDK
on:
  push:
    paths:
      - 'go/**'
      - 'go/**/**'
      - '.github/workflows/go.yml'

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: "1.17"

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Tests
      run: make test
