name: Golang HTTP Metrics CDK
on:
  push:
    paths:
      - 'golang/httpmetrics/**'
      - '.github/workflows/golang_httpmetrics.yml'

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: "1.17"

    - name: Checkout Repo
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-l9cdk-${{ hashFiles('golang/httpmetrics/go.sum') }}

    - name: Test
      run: cd golang/httpmetrics; go test -v ./...